export const config = {
    RPC_URL: 'https://rpc.serv.services',
    REST_URL: 'https://lcd.serv.services',
    EXPLORER_URL: 'https://tserv-explorer.tryethernal.com',
    NETWORK_NAME: 'SERV Protocol Testnet',
    NETWORK_TYPE: 'testnet',
    CHAIN_ID: 'serv_43970-1',
    CHAIN_NAME: 'SERV',
    COIN_DENOM: 'SERV',
    COIN_MINIMAL_DENOM: 'aservo',
    COIN_DECIMALS: 18,
    PREFIX: 'sx',
    COIN_TYPE: 118,
    COINGECKO_ID: 'serv',
    DEFAULT_GAS: 250000,
    GAS_PRICE_STEP_LOW: 0.005,
    GAS_PRICE_STEP_AVERAGE: 0.025,
    GAS_PRICE_STEP_HIGH: 0.08,
    FEATURES: ["eth-address-gen", "eth-key-sign"],
};
